<!DOCTYPE html>
<head>
<title>ELECTRICAL ENGINEERING STUDT MATERIALS</title>
<link rel="stylesheet" type="text/css" href="style.css">
    </head>
<style type="text/css">
	body{
    margin: 0;
    padding: 0;
    background: url(sm.jpg)no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    font-family: sans-serif;

}
h1{
	 margin: 0;
    padding: 0 0 20px;
    text-align: center;
    font-size: 22px;
    background-color: white;
    color: black;

}
article{

	width:auto;
	padding:10px;
	margin: 5px;
	overflow-x :auto;

}
div{
	float: center;
}

.tab1{
	background: #f5f5f5;
    
    font-family: sans-serif;
    font-weight:
	border:2px soldi black;
	 
    padding: 40px;
	border-radius: 10px;
	margin:80px;
	overflow-x: auto;
    display: inline-block;
    
}
.tab2{
    background: #f5f5f5;
    font-family: sans-serif;
    font-weight:
    border:2px soldi black;
     
    padding: 40px;
    border-radius: 10px;
    margin:80px;
    overflow-x: auto;
    display: inline-block;

}

table ,tr ,td{
    border-collapse: collapse;
    padding: 20px;
    float: center;
}
td{
    text-align: left;
}
h3{
    text-shadow: 4px 4px 5px BLUE; 
    font-size: 20px;
    background: gray;
    padding: 10px;
    border-radius: 10px;
   
}
<>    
</style>    

<body >
<?php
   include 'headers.php';
 ?>
  <h1 style="text-align: center;font-size: 60px">DOWNLOAD YOUR STUDY MATERIALS AND QUESTION PAPERS FOR ELECTRICAL ENGINEERING </h1>
 <article>
<section style="text-align: center;" style="width: 600px;">
 <div class="tab1">
<table border="1px solid gray;" style="width: 600px;">
  <h3>SEMESTER 3</h3>
    <tr>
        <th>SUBJECTS</th>
         <th>DOWNLOAD</th>
    
    <tr>
        <td>ELECTRICAL CIRCUIT THEORY</td><br>
        <td><a href="New folder\eee\3rdsem\Electrical Circuit Theory.pdf" download="">Click Here</a>
     </td>
     <tr>   
        <td>ELECTRICAL MACHINES - 1</td>
        <td><a href="New folder\eee\3rdsem\Electrical Machines I.pdf">Click Here</a>
     </td>
        </tr>
       <!-- <tr><td>ELECTRICAL MACHINES II </td><td><a href="New folder\eee\3rdsem\EEE Part-II(Electrical Machines II).pdf">Click Here</a>
     </td></tr>-->
        
        <tr><td>QUESTION PAPER(SEMESTER 3)</td><td><a href="Questions\eee\3rd sem\questions(eee-3rdsem).zip">Click Here</a>
     </td></tr>
    </tr>
    </tr>
  </table>
 </div>
    <div class="tab1">
<table border="1px solid gray;" style="width: 600px;">
  <h3>SEMESTER 4</h3>
    <tr>
        <th>SUBJECTS</th>
         <th>DOWNLOAD</th>
    
    <tr>
        <td>ELECTRICAL MACHINES - 2</td><br>
        <td><a href="New folder\eee\4thsem\EEE Part-II(Electrical Machines II).pdf" download="">Click Here</a>
     </td>
     <tr>   
        <td>MEASUREMENTS AND INSTRUMENTS</td>
        <td><a href="New folder\eee\4thsem\MEASUREMENTS AND INSTRUMENTS.pdf">Click Here</a>
     </td>
        </tr>
       <!-- <tr><td>DIGITAL ELECTRONICS*</td><td><a href="">Click Here</a>
     </td></tr>-->
        
        <tr><td>TRANSDUCERS AND SIGNAL CONDITIONERS</td><td><a href="New folder\eee\4thsem\Transducers and Signal Conditioners.pdf">Click Here</a>
     </td></tr>

        <tr><td>QUESTION PAPER(SEMESTER 4)</td><td><a href="Questions\eee\4th sem\questions(eee-4thsem).zip">Click Here</a>
     </td></tr>
    </tr>
    </tr>
  </table>
 </div>
 <div class="tab1">
<table border="1px solid gray;" style="width: 600px;">
  <h3>SEMESTER 5</h3>
    <tr>
        <th>SUBJECTS</th>
         <th>DOWNLOAD</th>
    
    <tr>
        <td>CONTROL OF ELECTRICAL MACHINES</td><br>
        <td><a href="New folder\eee\5thsem\Control of Electrical Machines.pdf" download="">Click Here</a>
     </td>
     <tr>   
        <td>ELECTRICAL ESTIMATION AND ENERGY AUDITING</td>
        <td><a href="New folder\eee\5thsem\Electrical Estimation & Energy Auditing.pdf">Click Here</a>
     </td>
        </tr>
        <tr><td>GENERATION,TRANSMISSION AND SWITCH GEAR</td><td><a href="New folder\eee\5thsem\Generation, Transmission & Switch Gear.pdf">Click Here</a>
     </td></tr>
        
        <tr><td>LOGIC CONTROLLER</td><td><a href="New folder\eee\5thsem\Programmable Logic Controller.pdf">Click Here</a>
     </td></tr>

        <tr><td>QUESTION PAPER(SEMESTER 5)</td><td><a href="Questions\eee\5th sem\questions(eee-5thsem).zip">Click Here</a>
     </td></tr>
    </tr>
    </tr>
  </table>
 </div><div class="tab1">
<table border="1px solid gray;" style="width: 600px;">
  <h3>SEMESTER 6</h3>
    <tr>
        <th>SUBJECTS</th>
         <th>DOWNLOAD</th>
    
    <tr>
        <td>DISTRIBUTION AND UTILIZATION</td><br>
        <td><a href="New folder\eee\6thsem\Distribution & Utilization.pdf" download="">Click Here</a>
     </td>
     <tr>   
        <td>OPERATION AND MAINTENANCE OF ELECTRICAL<br> EQUIPMENTS</td>
        <td><a href="New folder\eee\6thsem\Operation & Maintenance of Electrical Equipment.pdf">Click Here</a>
     </td>
        </tr>
        <tr><td>POWER ELECTRONICS  </td><td><a href="New folder\eee\6thsem\Power Electronics.pdf">Click Here</a>
     </td></tr>
        
        <tr><td>QUESTION PAPER(SEMESTER 6)</td><td><a href="Questions\eee\6th sem\questions(eee-6thsem).zip">Click Here</a>
     </td></tr>
    </tr>
    </tr>
  </table>
 </div>
</section>
</article>
